### ISSUE TITLE
getting certificate onto phone

### ISSUE THREAD

**Issue by gkchim** [sdavides/AqaraPOST-Homeassistant#1]
Thank you for this. Really great tutorial. Really appreciate your efforts. please can you give more details on how you load the certificate onto the android phone. (should the CA certificate be saved as a '.cert', or '.pem' file?

Thanks

**Comment by sdavides** [comment]
on my phone pem, it depends on your smartphone, download the file to your phone and search for install certificate in the settings

**Comment by sdavides** [comment]
For some phones you need to enable developer settings

**Comment by gkchim** [comment]
thanks. Will try again tomorrow and let you know how it does.
________________________________

**Comment by gkchim** [comment]
Thanks - I have managed to load certificate I am almost there. I have tried to complete the Node Red stage, but i am getting errors:

on replacing my details in Node Red, there are two things i am not sure about.

1) in Burp Suite, it gives me "Area: EU". However in the Node Red flow, it asks for country, how should i deal with this?
2) in Node Red, it asks for subject id begining with 'lumi1.".  However, in burp, i find 2 subject id. the first begins with "lumi.1" the other begins with "lumi.5". Does it matter which one i should use?

```

24/02/2024, 15:49:37 [node: change dataKey = friendly-resource](http://192.XXXX:8123/api/hassio_ingress/LZtPnAc-ppO5POKB9BJwnFOH4tqhAnmzbCBwjQzOT1o/#) function : (error)
"TypeError: Cannot read properties of undefined (reading 'attr')"

24/02/2024, 15:49:42[node: set eventlog](http://192.xxxx:8123/api/hassio_ingress/LZtPnAc-ppO5POKB9BJwnFOH4tqhAnmzbCBwjQzOT1o/#)
function : (error)
"TypeError: Cannot read properties of undefined (reading 'resourceId')"
24/02/2024, 15:49:52[node: change dataKey = friendly-resource](http://192.33:8123/api/hassio_ingress/LZtPnAc-ppO5POKB9BJwnFOH4tqhAnmzbCBwjQzOT1o/#)
function : (error)
"TypeError: Cannot read properties of undefined (reading 'dataKey')"
24/02/2024, 15:50:02[node: Camera G3 Face Know](http://192.:8123/api/hassio_ingress/LZtPnAc-ppO5POKB9BJwnFOH4tqhAnmzbCBwjQzOT1o/#)
msg : error
"InputError: Attribute: TypeError: Cannot read properties of undefined (reading 'faceName')"



```

**Comment by sdavides** [comment]
lumi1 and lumi5 are the devices you have, usually the mac address.
You can find all the necessary data in burp suite.
Remember that the flow is developed for camera-hub g3, what device do you have?

**Comment by sdavides** [comment]
If you have not set any facial recognition on the G3 camera, disable this node "Camera G3 Face Know"

**Comment by sdavides** [comment]
country into node red is for time format

**Comment by gkchim** [comment]
> lumi1 and lumi5 are the devices you have, usually the mac address. You can find all the necessary data in burp suite. Remember that the flow is developed for camera-hub g3, what device do you have?

thanks. I have camera-hub g3. maybe the second mac address is for a contact sensor i have currently linked.

**Comment by gkchim** [comment]
Also, i cannot see anywhere in Node-Red to put in the 'client id' - should there be somewhere i put this?

**Comment by sdavides** [comment]
es-ES
en-UK
de-DE
it-IT
pt-PT
es-ES

client ID is not needed, use automatic configuration.

otherwise you can put manually:
![immagine](https://github.com/sdavides/AqaraPOST-Homeassistant/assets/31100253/9beabf45-0c84-4a1d-8877-d1ea5f023061)

**Comment by gkchim** [comment]
So,  I am trying to do a little bit of debugging and added 2 debugging nodes:

![image](https://github.com/sdavides/AqaraPOST-Homeassistant/assets/45492116/67815386-0746-4e3a-b360-451340644054)


here is the output from the second node. indicating a problem

![image](https://github.com/sdavides/AqaraPOST-Homeassistant/assets/45492116/b9eef83e-a711-4124-a15d-0b215adfb892)

Here is the debug node 1 output, which shows the payload going into the debug mode. Can you see any issues here?

![image](https://github.com/sdavides/AqaraPOST-Homeassistant/assets/45492116/c2791e88-cbb8-420f-81ee-6ca21e577c72)

**Comment by gkchim** [comment]
I have added two more nodes.

![image](https://github.com/sdavides/AqaraPOST-Homeassistant/assets/45492116/deb485f7-2667-4776-81b4-58673bd38817)


It seems problem is coming at the the convert time stage/node:

![image](https://github.com/sdavides/AqaraPOST-Homeassistant/assets/45492116/b7c56b0b-d511-4f19-9c66-4f713cab2c09)

this is what i have for my country. 

en-UK
![image](https://github.com/sdavides/AqaraPOST-Homeassistant/assets/45492116/3d5df848-dd6d-4a1a-bf0d-518b947fb502)

**Comment by sdavides** [comment]
sorry, so I can't help you, I should have your data to do some tests, have you tried with time it-IT?

**Comment by sdavides** [comment]
basically you have to analyze the request on burp and replicate it, the time conversion is not part of the burp request.

**Comment by sdavides** [comment]
en-UK is correct

**Comment by gkchim** [comment]
> sorry, so I can't help you, I should have your data to do some tests, have you tried with time it-IT?

just tried this, with no change

**Comment by sdavides** [comment]
if you want to give me the data, create an aqara account with the devices at the end delete the account and create another one for you

**Comment by gkchim** [comment]
> if you want to give me the data, create an aqara account with the devices at the end delete the account and create another one for you

Cheers. I'll do that

**Comment by sdavides** [comment]
sent

**Comment by gkchim** [comment]
sorry, please send again: 3s5i9nah@duck.com

**Comment by gkchim** [comment]
Thank you - this now works. after resetting my account and trying different details all now works!  Thank you very much. I think it was my subject id that was incorrect

**Comment by sdavides** [comment]
yes you wrote lumi.1xxx instead of lumi1.xxx
