### ISSUE TITLE
Missing Attribute from API call results in Camera Config G3 sensor to fail

### ISSUE THREAD

**Issue by HA-Roberto** [sdavides/AqaraPOST-Homeassistant#12]
The flow intended to update the Camera Config G3 sensor requests for 19 attributes but my camera was only returning an array of 18 elements [0, 17].
<img width="709" alt="image" src="https://github.com/user-attachments/assets/7d466a26-0f7d-447e-aa09-15d2551b068c">

The result was that the Camera Config G3 sensor was unable to find an attribute value and would fail to update the sensor completely and would return an error 
`"TypeError: Cannot read properties of undefined (reading '0')"`

I have updated the function to request all available returned attributes from the call 

Updated Function code:

> catch array id [19] > json with name=id

```
const resultLength = msg.payload.result.length; 

for (let i = 0; i < resultLength; i++) {
    let attrName = msg.payload.result[i].attr;
    msg.payload[attrName] = msg.payload.result[i];
}

node.send(msg);

return;
```

You will also need to add a new function node between the JSON node and the Camera Config G3 node.
<img width="430" alt="image" src="https://github.com/user-attachments/assets/039a343a-a4c4-465e-89c5-e95b460882a5">

The function will have the code:
```
let newPayload = {
    state: "Camera G3 config",
    attributes: {}
};


for (let i = 0; i < msg.payload.result.length; i++) {
    let attrName = msg.payload.result[i].attr;
    let attrValue = msg.payload.result[i].value;

    if (attrName === 'sdcard_status') {
        try {
            newPayload.attributes['sd totalsize'] = msg.payload.result[i].value.totalsize;
            newPayload.attributes['sd freesize'] = msg.payload.result[i].value.freesize;
        } catch (error) {

            node.warn("Error parsing sdcard_status JSON:");
        }
    } else {
        newPayload.attributes[attrName] = attrValue;
    }
}

msg.payload = newPayload; 

return msg;
```

Finally, you can remove all of the attributes from the Camera Config G3 node as they will now be populated from the new function node that was created.
<img width="503" alt="image" src="https://github.com/user-attachments/assets/c87f3f65-f218-4acf-b215-84c1d01c0da8">

**Comment by sdavides** [comment]
`const resultLength = msg.payload.result.length; 

for (let i = 0; i < resultLength; i++) {
    let attrName = msg.payload.result[i].attr;
    msg.payload[attrName] = msg.payload.result[i];
}

node.send(msg);

  return;`

Approved

**Comment by sdavides** [comment]
update complete
