### ISSUE TITLE
Sync Issue

### ISSUE THREAD

**Issue by brentgl** [sdavides/AqaraPOST-Homeassistant#13]
Hi
Fantastic flow!
I am having a problem where any change I make to the camera thru the Aqara hub is showing fine in the entities (I used auto-entities with camera_g3 to display all for now), but if I change anything in the entities in Home Assistant (or PTZ control the camera for example) it isn't being reflected in the App and on the G3.

I changed the inject node (boot +15s) to add the refresh interval to repeat every 1 second.

Is there something obvious I missed out on to cause this?
Thanks
Brent

**Comment by sdavides** [comment]
no response
