### ISSUE TITLE
InputError: Attribute: TypeError: Cannot read properties of undefined (reading 'value')

### ISSUE THREAD

**Issue by brentgl** [sdavides/AqaraPOST-Homeassistant#14]
Hi
running on Aqara G3 with firmware 3.3.9 - I tried to upgrade to latest as per your instructions but keep getting an error when running the script (left an issue on that github also).

I installed the latest flow with the correction (catch array id > json with name=id) just added  but am getting constant error in debug.  I also tried with and without adding the other function he spoke about in his github issue same error

InputError: Attribute: TypeError: Cannot read properties of undefined (reading 'value')
on nodes Camera G3 Info and Camera G3 config (repeating every 2 seconds as that is my refresh interval I set)

Any ideas? The camera control works ok for movement

Thanks

**Comment by sdavides** [comment]
It's so difficult to understand the problem, can you figure out which node reports the error? 
did you add the debug node?
I need your value (Token,AppID, ecc ) to help you.

**Comment by brentgl** [comment]
It's the first camera config after autostart on boot +15s
![image_2024-09-27_075634812](https://github.com/user-attachments/assets/d2289b33-2eba-49b3-a1ab-ef4ca42547c5)
and the camera info at the end of autostart on boot +30s
![Screenshot 2024-09-27 075445](https://github.com/user-attachments/assets/8afdeee8-5958-4ed1-bbd1-219ca8a0ba20)


G3 Config debug:
`{"result":[{"timeStamp":1727362619605,"attr":"mdtrigger_enable","value":true,"subjectId":"lumi1.54ef44374601"},{"timeStamp":1727362621239,"attr":"pets_detect_enable","value":true,"subjectId":"lumi1.54ef44374601"},{"timeStamp":1727346054964,"attr":"cloud_small_video","value":"0","subjectId":"lumi1.54ef44374601"},{"timeStamp":1727334882234,"attr":"ptz_cruise_enable","value":false,"subjectId":"lumi1.54ef44374601"},{"timeStamp":1727346054964,"attr":"alarm_bell_volume","value":"0","subjectId":"lumi1.54ef44374601"},{"timeStamp":1727362910044,"attr":"gesture_detect_enable","value":false,"subjectId":"lumi1.54ef44374601"},{"timeStamp":1727346497813,"attr":"pets_track_enable","value":false,"subjectId":"lumi1.54ef44374601"},{"timeStamp":1727346481705,"attr":"set_video","value":true,"subjectId":"lumi1.54ef44374601"},{"timeStamp":1727417847172,"attr":"device_wifi_rssi","value":"-51","subjectId":"lumi1.54ef44374601"},{"timeStamp":1727362910041,"attr":"face_detect_enable","value":true,"subjectId":"lumi1.54ef44374601"},{"timeStamp":1727346054964,"attr":"alarm_status","value":"0","subjectId":"lumi1.54ef44374601"},{"timeStamp":1727367626799,"attr":"gateway_deletion_setting","value":true,"subjectId":"lumi1.54ef44374601"},{"timeStamp":1727362620485,"attr":"human_detect_enable","value":true,"subjectId":"lumi1.54ef44374601"},{"timeStamp":1727346481758,"attr":"humans_track_enable","value":false,"subjectId":"lumi1.54ef44374601"},{"timeStamp":1727346481906,"attr":"soundtrigger_enable","value":true,"subjectId":"lumi1.54ef44374601"},{"timeStamp":1727367626799,"attr":"system_volume","value":"50","subjectId":"lumi1.54ef44374601"},{"timeStamp":1727334882459,"attr":"device_night_tip_light","value":true,"subjectId":"lumi1.54ef44374601"},{"timeStamp":1727417902519,"source":"15,,1727417902,,,","attr":"sdcard_status","value":{"freesize":26220,"othersize":27,"sdstatus":0,"totalsize":30420},"subjectId":"lumi1.54ef44374601"}],"code":0,"requestId":"5ae60ff3273d4987a4a8482f92ccdd30.54.17274179024645645","message":"Success","msgDetails":"Success","mdtrigger_enable":{"timeStamp":1727362619605,"attr":"mdtrigger_enable","value":true,"subjectId":"lumi1.54ef44374601"},"pets_detect_enable":{"timeStamp":1727362621239,"attr":"pets_detect_enable","value":true,"subjectId":"lumi1.54ef44374601"},"cloud_small_video":{"timeStamp":1727346054964,"attr":"cloud_small_video","value":"0","subjectId":"lumi1.54ef44374601"},"ptz_cruise_enable":{"timeStamp":1727334882234,"attr":"ptz_cruise_enable","value":false,"subjectId":"lumi1.54ef44374601"},"alarm_bell_volume":{"timeStamp":1727346054964,"attr":"alarm_bell_volume","value":"0","subjectId":"lumi1.54ef44374601"},"gesture_detect_enable":{"timeStamp":1727362910044,"attr":"gesture_detect_enable","value":false,"subjectId":"lumi1.54ef44374601"},"pets_track_enable":{"timeStamp":1727346497813,"attr":"pets_track_enable","value":false,"subjectId":"lumi1.54ef44374601"},"set_video":{"timeStamp":1727346481705,"attr":"set_video","value":true,"subjectId":"lumi1.54ef44374601"},"device_wifi_rssi":{"timeStamp":1727417847172,"attr":"device_wifi_rssi","value":"-51","subjectId":"lumi1.54ef44374601"},"face_detect_enable":{"timeStamp":1727362910041,"attr":"face_detect_enable","value":true,"subjectId":"lumi1.54ef44374601"},"alarm_status":{"timeStamp":1727346054964,"attr":"alarm_status","value":"0","subjectId":"lumi1.54ef44374601"},"gateway_deletion_setting":{"timeStamp":1727367626799,"attr":"gateway_deletion_setting","value":true,"subjectId":"lumi1.54ef44374601"},"human_detect_enable":{"timeStamp":1727362620485,"attr":"human_detect_enable","value":true,"subjectId":"lumi1.54ef44374601"},"humans_track_enable":{"timeStamp":1727346481758,"attr":"humans_track_enable","value":false,"subjectId":"lumi1.54ef44374601"},"soundtrigger_enable":{"timeStamp":1727346481906,"attr":"soundtrigger_enable","value":true,"subjectId":"lumi1.54ef44374601"},"system_volume":{"timeStamp":1727367626799,"attr":"system_volume","value":"50","subjectId":"lumi1.54ef44374601"},"device_night_tip_light":{"timeStamp":1727334882459,"attr":"device_night_tip_light","value":true,"subjectId":"lumi1.54ef44374601"},"sdcard_status":{"timeStamp":1727417902519,"source":"15,,1727417902,,,","attr":"sdcard_status","value":{"freesize":26220,"othersize":27,"sdstatus":0,"totalsize":30420},"subjectId":"lumi1.54ef44374601"}}`



G3 Info debug
`{"result":{"data":[{"dataKey":"14.119.85","time":1727346481906,"value":"1"},{"dataKey":"14.10.85","time":1727367626799,"value":"2"},{"dataKey":"4.59.85","time":1727334882475,"value":"0"},{"dataKey":"13.201.85","time":1727346054964,"value":"0"},{"dataKey":"14.125.85","time":1727334882458,"value":"0"},{"dataKey":"14.121.85","time":1727334882234,"value":"0"},{"dataKey":"14.140.85","time":1727334882469,"value":"Medium"},{"dataKey":"deviceName","value":"Man Cave G3 Camera"},{"dataKey":"deviceId","value":"lumi1.54ef44374601"},{"dataKey":"14.109.85","time":1727334882466,"value":"{\"starttime\": \"00:00\",\"endtime\": \"23:59\",\"repeat\": [1,1,1,1,1,1,1]}"},{"dataKey":"14.4.85","time":1727362918941,"value":"Enable"},{"dataKey":"supportMaterial","value":"0"},{"dataKey":"4.51.85","time":1727334882463,"value":"0"},{"dataKey":"14.20.85","time":1727354669080,"value":{"mode":"Stop","cover":true}},{"dataKey":"subDeviceCount","value":"0"},{"dataKey":"8.0.2327","time":1727334882234,"value":"Enable"},{"dataKey":"sceneCount","value":"0"},{"dataKey":"4.55.85","time":1727334882472,"value":"0"},{"dataKey":"14.112.85","time":1727334882234,"value":"{\"x_begin\":3,\"y_end\":8,\"y_begin\":0,\"x_end\":11}"},{"dataKey":"firmwareVersion","value":"3.3.9_0011.0013"},{"dataKey":"isExistsFaq","value":"0"},{"dataKey":"14.76.85","time":1727362910044,"value":"0"},{"dataKey":"14.116.85","time":1727334882475,"value":"60"},{"dataKey":"14.118.85","time":1727334882234,"value":"0"},{"dataKey":"4.89.85","time":1727334882234,"value":"Disable"},{"dataKey":"14.11.85","time":1727367626799,"value":"50"},{"dataKey":"4.58.85","time":1727334882475,"value":"0"},{"dataKey":"14.108.85","time":1727334882466,"value":"60"},{"dataKey":"14.126.85","time":1727367626876,"value":"0.0.0"},{"dataKey":"14.105.85","time":1727334882464,"value":"60"},{"dataKey":"14.122.85","time":1727346481758,"value":"0"},{"dataKey":"4.75.85","time":1727334882477,"value":"0"},{"dataKey":"4.50.85","time":1727334882463,"value":"0"},{"dataKey":"4.54.85","time":1727334882472,"value":"0"},{"dataKey":"14.21.85","time":1727367626799,"value":"5162041"},{"dataKey":"8.0.2032","time":1727334882459,"value":"1"},{"dataKey":"14.115.85","time":1727334882474,"value":"{\"starttime\": \"00:00\",\"endtime\": \"23:59\",\"repeat\": [1,1,1,1,1,1,1]}"},{"dataKey":"14.77.85","time":1727362620485,"value":"1"},{"dataKey":"14.111.85","time":1727334882472,"value":"{\"starttime\": \"00:00\",\"endtime\": \"23:59\",\"repeat\": [1,1,1,1,1,1,1]}"},{"dataKey":"8.0.2158","time":1727367626799,"value":"1"},{"dataKey":"14.73.85","time":1727346185481,"value":"Auto"},{"dataKey":"14.90.85","time":1727348254779,"value":"0"},{"dataKey":"14.117.85","time":1727334882476,"value":"{\"starttime\": \"00:00\",\"endtime\": \"23:59\",\"repeat\": [1,1,1,1,1,1,1]}"},{"dataKey":"4.63.85","time":1727334882460,"value":"Disable"},{"dataKey":"4.57.85","time":1727334882474,"value":"0"},{"dataKey":"14.146.85","time":1727334882234,"value":"60"},{"dataKey":"14.104.85","time":1727355052900,"value":"Medium"},{"dataKey":"14.107.85","time":1727334882465,"value":"{\"starttime\": \"00:00\",\"endtime\": \"23:59\",\"repeat\": [1,1,1,1,1,1,1]}"},{"dataKey":"14.123.85","time":1727346497813,"value":"0"},{"dataKey":"positionName","value":"Default Room"},{"dataKey":"14.67.85","time":1727367626832,"value":{"ip":"192.168.1.201","mac":"54:EF:44:37:46:01","rssi":-54,"ssid":"highspeed"}},{"dataKey":"4.76.85","time":1727354653766,"value":"Enable"},{"dataKey":"linkageCount","value":"0"},{"dataKey":"8.0.2108","time":1727346054964,"value":"0"},{"dataKey":"4.48.85","time":1727334882477,"value":"Disable"},{"dataKey":"4.53.85","time":1727334882466,"value":"0"},{"dataKey":"parentDeviceId","value":""},{"dataKey":"manualUrl","value":"https://prd.aqara.com/manual/?mid=manual.1054810246827048960"},{"dataKey":"14.88.701","time":1727346054964,"value":"{  \"mode\": 0,  \"x\": 999,  \"y\": 999}"},{"dataKey":"14.34.85","time":1727346054964,"value":"0"},{"dataKey":"14.133.85","time":1727346054964,"value":"0"},{"dataKey":"14.110.85","time":1727334882472,"value":"60"},{"dataKey":"14.70.85","time":1727362619605,"value":"1"},{"dataKey":"14.38.85","time":1727334882234,"value":"{\"starttime\":\"00:00\",\"endtime\":\"23:59\",\"repeat\":[1,1,1,1,1,1,1]}"},{"dataKey":"14.114.85","time":1727334882474,"value":"60"},{"dataKey":"8.0.2302","time":1727346054964,"value":"0"},{"dataKey":"14.78.85","time":1727362621239,"value":"1"},{"dataKey":"upper_mac","value":"54EF44374601"},{"dataKey":"14.86.85","time":1727334882476,"value":"Enable"},{"dataKey":"14.124.85","time":1727334882234,"value":"0"},{"dataKey":"14.61.85","time":1727346054964,"value":"0"},{"dataKey":"14.65.85","time":1727346054964,"value":"80"},{"dataKey":"14.106.85","time":1727334882465,"value":"{\"detect_region\":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]}"},{"dataKey":"modelName","value":"Camera Hub G3"},{"dataKey":"14.68.85","time":1727334882459,"value":"0"},{"dataKey":"4.52.85","time":1727334882465,"value":"0"},{"dataKey":"13.25.85","time":1727418000135,"source":"15,,1727418000,,,","value":{"freesize":26220,"othersize":27,"sdstatus":0,"totalsize":30420}},{"dataKey":"positionId","value":"real2.959464803724271616"},{"dataKey":"4.56.85","time":1727334882474,"value":"0"},{"dataKey":"14.75.85","time":1727362910041,"value":"1"},{"dataKey":"14.113.85","time":1727334882473,"value":"{\"starttime\": \"00:00\",\"endtime\": \"23:59\",\"repeat\": [1,1,1,1,1,1,1]}"}],"name":"Man Cave G3 Camera","icon":"","state":1},"code":0,"requestId":"06405223262d4b0f911055eb8c5b3e23.54.17274180000668209","message":"Success","msgDetails":"Success","14.119.85":{"dataKey":"14.119.85","time":1727346481906,"value":"1"},"14.10.85":{"dataKey":"14.10.85","time":1727367626799,"value":"2"},"4.59.85":{"dataKey":"4.59.85","time":1727334882475,"value":"0"},"13.201.85":{"dataKey":"13.201.85","time":1727346054964,"value":"0"},"14.125.85":{"dataKey":"14.125.85","time":1727334882458,"value":"0"},"14.121.85":{"dataKey":"14.121.85","time":1727334882234,"value":"0"},"14.140.85":{"dataKey":"14.140.85","time":1727334882469,"value":"Medium"},"deviceName":{"dataKey":"deviceName","value":"Man Cave G3 Camera"},"deviceId":{"dataKey":"deviceId","value":"lumi1.54ef44374601"},"14.109.85":{"dataKey":"14.109.85","time":1727334882466,"value":"{\"starttime\": \"00:00\",\"endtime\": \"23:59\",\"repeat\": [1,1,1,1,1,1,1]}"},"14.4.85":{"dataKey":"14.4.85","time":1727362918941,"value":"Enable"},"supportMaterial":{"dataKey":"supportMaterial","value":"0"},"4.51.85":{"dataKey":"4.51.85","time":1727334882463,"value":"0"},"14.20.85":{"dataKey":"14.20.85","time":1727354669080,"value":{"mode":"Stop","cover":true}},"subDeviceCount":{"dataKey":"subDeviceCount","value":"0"},"8.0.2327":{"dataKey":"8.0.2327","time":1727334882234,"value":"Enable"},"sceneCount":{"dataKey":"sceneCount","value":"0"},"4.55.85":{"dataKey":"4.55.85","time":1727334882472,"value":"0"},"14.112.85":{"dataKey":"14.112.85","time":1727334882234,"value":"{\"x_begin\":3,\"y_end\":8,\"y_begin\":0,\"x_end\":11}"},"firmwareVersion":{"dataKey":"firmwareVersion","value":"3.3.9_0011.0013"},"isExistsFaq":{"dataKey":"isExistsFaq","value":"0"},"14.76.85":{"dataKey":"14.76.85","time":1727362910044,"value":"0"},"14.116.85":{"dataKey":"14.116.85","time":1727334882475,"value":"60"},"14.118.85":{"dataKey":"14.118.85","time":1727334882234,"value":"0"},"4.89.85":{"dataKey":"4.89.85","time":1727334882234,"value":"Disable"},"14.11.85":{"dataKey":"14.11.85","time":1727367626799,"value":"50"},"4.58.85":{"dataKey":"4.58.85","time":1727334882475,"value":"0"},"14.108.85":{"dataKey":"14.108.85","time":1727334882466,"value":"60"},"14.126.85":{"dataKey":"14.126.85","time":1727367626876,"value":"0.0.0"},"14.105.85":{"dataKey":"14.105.85","time":1727334882464,"value":"60"},"14.122.85":{"dataKey":"14.122.85","time":1727346481758,"value":"0"},"4.75.85":{"dataKey":"4.75.85","time":1727334882477,"value":"0"},"4.50.85":{"dataKey":"4.50.85","time":1727334882463,"value":"0"},"4.54.85":{"dataKey":"4.54.85","time":1727334882472,"value":"0"},"14.21.85":{"dataKey":"14.21.85","time":1727367626799,"value":"5162041"},"8.0.2032":{"dataKey":"8.0.2032","time":1727334882459,"value":"1"},"14.115.85":{"dataKey":"14.115.85","time":1727334882474,"value":"{\"starttime\": \"00:00\",\"endtime\": \"23:59\",\"repeat\": [1,1,1,1,1,1,1]}"},"14.77.85":{"dataKey":"14.77.85","time":1727362620485,"value":"1"},"14.111.85":{"dataKey":"14.111.85","time":1727334882472,"value":"{\"starttime\": \"00:00\",\"endtime\": \"23:59\",\"repeat\": [1,1,1,1,1,1,1]}"},"8.0.2158":{"dataKey":"8.0.2158","time":1727367626799,"value":"1"},"14.73.85":{"dataKey":"14.73.85","time":1727346185481,"value":"Auto"},"14.90.85":{"dataKey":"14.90.85","time":1727348254779,"value":"0"},"14.117.85":{"dataKey":"14.117.85","time":1727334882476,"value":"{\"starttime\": \"00:00\",\"endtime\": \"23:59\",\"repeat\": [1,1,1,1,1,1,1]}"},"4.63.85":{"dataKey":"4.63.85","time":1727334882460,"value":"Disable"},"4.57.85":{"dataKey":"4.57.85","time":1727334882474,"value":"0"},"14.146.85":{"dataKey":"14.146.85","time":1727334882234,"value":"60"},"14.104.85":{"dataKey":"14.104.85","time":1727355052900,"value":"Medium"},"14.107.85":{"dataKey":"14.107.85","time":1727334882465,"value":"{\"starttime\": \"00:00\",\"endtime\": \"23:59\",\"repeat\": [1,1,1,1,1,1,1]}"},"14.123.85":{"dataKey":"14.123.85","time":1727346497813,"value":"0"},"positionName":{"dataKey":"positionName","value":"Default Room"},"14.67.85":{"dataKey":"14.67.85","time":1727367626832,"value":{"ip":"192.168.1.201","mac":"54:EF:44:37:46:01","rssi":-54,"ssid":"highspeed"}},"4.76.85":{"dataKey":"4.76.85","time":1727354653766,"value":"Enable"},"linkageCount":{"dataKey":"linkageCount","value":"0"},"8.0.2108":{"dataKey":"8.0.2108","time":1727346054964,"value":"0"},"4.48.85":{"dataKey":"4.48.85","time":1727334882477,"value":"Disable"},"4.53.85":{"dataKey":"4.53.85","time":1727334882466,"value":"0"},"parentDeviceId":{"dataKey":"parentDeviceId","value":""},"manualUrl":{"dataKey":"manualUrl","value":"https://prd.aqara.com/manual/?mid=manual.1054810246827048960"},"14.88.701":{"dataKey":"14.88.701","time":1727346054964,"value":"{  \"mode\": 0,  \"x\": 999,  \"y\": 999}"},"14.34.85":{"dataKey":"14.34.85","time":1727346054964,"value":"0"},"14.133.85":{"dataKey":"14.133.85","time":1727346054964,"value":"0"},"14.110.85":{"dataKey":"14.110.85","time":1727334882472,"value":"60"},"14.70.85":{"dataKey":"14.70.85","time":1727362619605,"value":"1"},"14.38.85":{"dataKey":"14.38.85","time":1727334882234,"value":"{\"starttime\":\"00:00\",\"endtime\":\"23:59\",\"repeat\":[1,1,1,1,1,1,1]}"},"14.114.85":{"dataKey":"14.114.85","time":1727334882474,"value":"60"},"8.0.2302":{"dataKey":"8.0.2302","time":1727346054964,"value":"0"},"14.78.85":{"dataKey":"14.78.85","time":1727362621239,"value":"1"},"upper_mac":{"dataKey":"upper_mac","value":"54EF44374601"},"14.86.85":{"dataKey":"14.86.85","time":1727334882476,"value":"Enable"},"14.124.85":{"dataKey":"14.124.85","time":1727334882234,"value":"0"},"14.61.85":{"dataKey":"14.61.85","time":1727346054964,"value":"0"},"14.65.85":{"dataKey":"14.65.85","time":1727346054964,"value":"80"},"14.106.85":{"dataKey":"14.106.85","time":1727334882465,"value":"{\"detect_region\":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]}"},"modelName":{"dataKey":"modelName","value":"Camera Hub G3"},"14.68.85":{"dataKey":"14.68.85","time":1727334882459,"value":"0"},"4.52.85":{"dataKey":"4.52.85","time":1727334882465,"value":"0"},"13.25.85":{"dataKey":"13.25.85","time":1727418000135,"source":"15,,1727418000,,,","value":{"freesize":26220,"othersize":27,"sdstatus":0,"totalsize":30420}},"positionId":{"dataKey":"positionId","value":"real2.959464803724271616"},"4.56.85":{"dataKey":"4.56.85","time":1727334882474,"value":"0"},"14.75.85":{"dataKey":"14.75.85","time":1727362910041,"value":"1"},"14.113.85":{"dataKey":"14.113.85","time":1727334882473,"value":"{\"starttime\": \"00:00\",\"endtime\": \"23:59\",\"repeat\": [1,1,1,1,1,1,1]}"},"sensivity_suond":{"dataKey":"14.140.85","time":1727334882469,"value":"Medium"},"rec_mode":{"dataKey":"14.20.85","time":1727354669080,"value":{"mode":"Stop","cover":true}},"catdog_freq":{"dataKey":"14.116.85","time":1727334882475,"value":"60"},"volume":{"dataKey":"14.11.85","time":1727367626799,"value":"50"},"suond_freq":{"dataKey":"14.108.85","time":1727334882466,"value":"60"},"motion_freq":{"dataKey":"14.105.85","time":1727334882464,"value":"60"},"night_video":{"dataKey":"14.73.85","time":1727346185481,"value":"Auto"},"sensitivity":{"dataKey":"14.104.85","time":1727355052900,"value":"Medium"},"frame":{"dataKey":"4.76.85","time":1727354653766,"value":"Enable"},"gestneedface":{"dataKey":"4.48.85","time":1727334882477,"value":"Disable"},"rete":{"dataKey":"14.67.85","time":1727367626832,"value":{"ip":"192.168.1.201","mac":"54:EF:44:37:46:01","rssi":-54,"ssid":"highspeed"}},"sdmemory":{"dataKey":"13.25.85","time":1727418000135,"source":"15,,1727418000,,,","value":{"freesize":26220,"othersize":27,"sdstatus":0,"totalsize":30420}},"face_freq":{"dataKey":"14.110.85","time":1727334882472,"value":"60"},"human_freq":{"dataKey":"14.114.85","time":1727334882474,"value":"60"},"muteaudio":{"dataKey":"4.63.85","time":1727334882460,"value":"Disable"},"timestamp":{"dataKey":"14.4.85","time":1727362918941,"value":"Enable"},"ark_mode":{"dataKey":"8.0.2327","time":1727334882234,"value":"Enable"},"poweroff_memory":{"dataKey":"14.86.85","time":1727334882476,"value":"Enable"},"device_offline_notif":{"dataKey":"4.89.85","time":1727334882234,"value":"Disable"}}`

Is the token and appid sensitive? if not I can post away here
Thanks
Brent

**Comment by sdavides** [comment]
send me token in private

**Comment by brentgl** [comment]
cant do private on github unless you know how

the info in config is good - country I set to en-UK even though the zap log says area EU
I tried with auto user and manually entering the UserId.

It is getting my local IP and MAC
"ip":"192.168.1.201","mac":"54:EF:44:37:46:01"
which ties in with my subject id I set:

lumi1.54ef44374601

Seems to be a rogue value in the array sent but I can seem to track it down


Brent

**Comment by sdavides** [comment]
davidepalank@gmail.com

**Comment by brentgl** [comment]
sent

**Comment by sdavides** [comment]
I created the last flow update for alarm_bell_index hot found

Fix alarm_bell - sdcard not found
