### ISSUE TITLE
Aiuto in configurazione

### ISSUE THREAD

**Issue by Sirman13** [sdavides/AqaraPOST-Homeassistant#15]
Ciao! Ho correttamente configurato ed acquisito i valori dagli script in python, dal nodered vedo che si logga ma attualmente ricevo questi errori:

11 Nov 10:26:24 - [error] [ha-sensor:Aqara UserID] InputError: Integration not loaded
11 Nov 10:26:30 - [error] [ha-sensor:Camera G3 config] InputError: Integration not loaded
11 Nov 10:26:36 - [error] [ha-sensor:Camera G3 log] InputError: Integration not loaded
11 Nov 10:26:36 - [error] [ha-sensor:Camera G3 log last3] InputError: Integration not loaded
11 Nov 10:26:36 - [error] [ha-sensor:Camera G3 log last2] InputError: Integration not loaded
11 Nov 10:26:36 - [error] [ha-sensor:Camera G3 log last1] InputError: Integration not loaded
11 Nov 10:26:46 - [error] [ha-sensor:Camera G3 Info] InputError: Integration not loaded
11 Nov 10:26:56 - [error] [ha-sensor:Camera G3 Face Know] InputError: Integration not loaded
11 Nov 10:27:06 - [error] [ha-sensor:Aqara Smart log Autom] InputError: Integration not loaded
11 Nov 10:27:16 - [error] [ha-sensor:Aqara MyDevice] InputError: Integration not loaded

Poi non c'è una guida su come importare la dashboard che vedo nel readme.md.. 
Grazie anticipatamente per le risposte

**Comment by sdavides** [comment]
hai installato node-companion?
la dashboard è un esempio creata con more-info-card

**Comment by Sirman13** [comment]
Grazie per la risposta istantanea.. No, non ho installato node-companion, lo installo subito! Grazie

**Comment by sdavides** [comment]
C'è scritto sulla guida, da HACS.

Probabilmente per la porta già occupata, dai log cosa dice?

**Comment by Sirman13** [comment]
[34m-----------------------------------------------------------[0m
[34m Add-on: Node-RED[0m
[34m Flow-based programming for the Internet of Things[0m
[34m-----------------------------------------------------------[0m
[34m Add-on version: 18.1.1[0m
[32m You are running the latest version of this add-on.[0m
[34m System: Home Assistant OS 13.2  (amd64 / qemux86-64)[0m
[34m Home Assistant Core: 2024.11.1[0m
[34m Home Assistant Supervisor: 2024.11.2[0m
[34m-----------------------------------------------------------[0m
[34m Please, share the above information when looking for help[0m
[34m or support in, e.g., GitHub, forums or the Discord chat.[0m
[34m-----------------------------------------------------------[0m
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-customizations: starting
s6-rc: info: service init-customizations successfully started
s6-rc: info: service init-nodered: starting
[11:07:42] FATAL: [31m[0m
[11:07:42] FATAL: [31mSSL has been enabled using the 'ssl' option,[0m
[11:07:42] FATAL: [31mthis requires an SSL certificate file which is[0m
[11:07:42] FATAL: [31mconfigured using the 'certfile' option in the[0m
[11:07:42] FATAL: [31madd-on configuration.[0m
[11:07:42] FATAL: [31m[0m
[11:07:42] FATAL: [31mUnfortunately, the file specified in the[0m
[11:07:42] FATAL: [31m'certfile' option does not exist.[0m
s6-rc: info: service init-nodered successfully started
s6-rc: info: service nodered: starting
[11:07:42] FATAL: [31m[0m
s6-rc: info: service nodered successfully started
[11:07:42] FATAL: [31mPlease ensure the certificate file exists and[0m
[11:07:42] FATAL: [31mis placed in the '/ssl/' directory.[0m
[11:07:42] FATAL: [31m[0m
[11:07:42] FATAL: [31mIn case you don't have SSL yet, consider getting[0m
[11:07:42] FATAL: [31man SSL certificate or setting the 'ssl' option[0m
[11:07:42] FATAL: [31mto 'false' in case you are not planning on using[0m
[11:07:42] FATAL: [31mSSL with this add-on.[0m
[11:07:42] FATAL: [31m[0m
[11:07:42] FATAL: [31mCheck the add-on manual for more information.[0m
[11:07:42] FATAL: [31m[0m
s6-rc: warning: unable to start service init-nginx: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service nodered: stopping
[11:07:42] INFO: [32mService Node-RED exited with code 256 (by signal 15)[0m
s6-rc: info: service nodered successfully stopped
s6-rc: info: service init-nodered: stopping
s6-rc: info: service init-nodered successfully stopped
s6-rc: info: service init-customizations: stopping
s6-rc: info: service init-customizations successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by Sirman13** [comment]
Avevo SSL selezionato da Default, ho tolto la spunta e adesso è UP

**Comment by Sirman13** [comment]
Ho fatto il restart del flow, ricevo gli stessi errori nel log di Aqara post, noderd però adesso è attivo

**Comment by sdavides** [comment]
non ti capisco, ci sono i valori dentro config?

**Comment by Sirman13** [comment]
![Immagine 2024-11-11 112926](https://github.com/user-attachments/assets/232e6265-382b-4acb-b1a8-ceed49d9c005)

Questi sono i valori che ho inserito in config

**Comment by sdavides** [comment]
è corretto, qual'è il problema?
in node red ci sono errori?

aggiungi il nodo debug su un nodo blu
