### ISSUE TITLE
Gestures recognition support

### ISSUE THREAD

**Issue by piokaczo** [sdavides/AqaraPOST-Homeassistant#3]
Hello @sdavides - awesome work!

Is there a chance to get support of gestures recognition? It would be great to trigger HA actions depending on gestures recognized by camera.

**Comment by sdavides** [comment]
yes, you can do it in many ways, you can check the last log message, or the aqara automation logs and then set an automation: when the log entity changes to "example-message-log" ....

or a button that switches to on when it receives the certain log message by creating a node and creating the automation when the button switches to on ....

**Comment by piokaczo** [comment]
There is some issue with this as I am getting only one gesture recognition in logs (looking into all 3 log entities). There is information about gesture being recognised, then no following ones (tried different gestures as well). Once I turn on and off privacy and then made some gesture it is showing in logs - but again, only once and things seems to freeze with that.

**Comment by sdavides** [comment]
create an automation in aqara app with name "XXX" and search the automation logs for "XXX"

**Comment by piokaczo** [comment]
That is clear. The issue is that workflow seems to not get or parse more than one occurrence of gesture recognition. To parse next ones I have to do some other action with camera or restart workflow.

**Comment by sdavides** [comment]
you need to check the time attribute:

example every motion detecion

`alias: New autom
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.camera_g3_log
    attribute: time
condition:
  - condition: state
    entity_id: sensor.camera_g3_log
    attribute: eventlog
    state: Motion Detection
action:
  - service: notify.notify
    data:
      title: Motion Detection
      message: >-
        Motion Detection |
        {{now().strftime('%H:%M:%S')}}-{{now().strftime('%d/%m/%Y')}}
mode: single`

**Comment by piokaczo** [comment]
We’re talking about different things. This won’t work since node red workflow itself does not report next occurrence of any gesture recognition. It seems that there have to be other action or workflow restart to report any subsequent gesture recognition. I’m debugging straight in workflow - not in HA logs. Workflow does not report any gesture for minutes even if camera recognizes it.

**Comment by sdavides** [comment]
the flow requires the data to be read at startup, you must click the "update log aqara g3" button, 
or modify the inject node:

![immagine](https://github.com/sdavides/AqaraPOST-Homeassistant/assets/31100253/40ac4bbb-b85a-4921-9da3-0f11ed5226a0)

**Comment by piokaczo** [comment]
Oh. All clear. Thank you!

**Comment by sdavides** [comment]
I have an automation that presses the update button every movement detected by the pir camera sensor from the homekit to limit requests. bye
