### ISSUE TITLE
Multiple devices support

### ISSUE THREAD

**Issue by piokaczo** [sdavides/AqaraPOST-Homeassistant#4]
Hello,

How can I use multiple cameras with node-red workflow?

**Comment by sdavides** [comment]
create a new flow, change the "subjectid" to the new device, change name entity for homeassistant, deploy

**Comment by piokaczo** [comment]
Changing subjectid works yet still entities are shown once and second workflow overrides first one in HA.

I have changed all camera names in new workflow. Could you point me exactly where should changes be made?

**Comment by sdavides** [comment]
![immagine](https://github.com/sdavides/AqaraPOST-Homeassistant/assets/31100253/2a0440a1-d878-4895-876f-26069be9c7db)

![immagine](https://github.com/sdavides/AqaraPOST-Homeassistant/assets/31100253/9cd59ca5-459c-42ae-a32c-ab869c8af195)

**Comment by piokaczo** [comment]
Should I change something more or just that two entities you've shown? Unfortunately this does not solve initial issue. Still  only entities in HA for one camera.

**Comment by sdavides** [comment]
delete all flows, restart ha,
import the first flow, deploy,
import second flow, BEFORE deploying change node name, entity name, name friendly, deploy, restart node-red, restart node-companion, or restart homeassistant

**Comment by sdavides** [comment]
make sure you

"add new device"
![immagine](https://github.com/sdavides/AqaraPOST-Homeassistant/assets/31100253/eeddfaf3-f395-46ce-a59b-285d1cf7ba4f)

**Comment by piokaczo** [comment]
After fiddling with this for hours more I believe that issue lies in different place. When importing second workflow there is notification about some of the nodes already existing in workspace. This makes both flows interconnect, especially that config is set as global (not per flow). As I am new to Node Red I couldn't find any easy way to change all nodes ID's without writing a script or changing that manually so for now I'm giving up with more than one device.
Thank you for swift replies nevertheless! :)

**Comment by sdavides** [comment]
I added another flow for the second device

**Comment by piokaczo** [comment]
Awesome! I'll test this over weekend
