### ISSUE TITLE
Token Generation

### ISSUE THREAD

**Issue by Wh1terat** [sdavides/AqaraPOST-Homeassistant#5]
Happened to come across your project as someone I follow on GH starred your repo.
Pained me to see the hoops you're jumping through to get tokens.

I see you've come across some of my other work before (aqrootg3) 😸 
I wrote this a couple of years ago to grab firmware for aqara zigbee devices, but handles token generation.

https://gist.github.com/Wh1terat/c4a4c665d692af461796e5eee9f5461d

👍

**Comment by sdavides** [comment]
wow that was what I was looking for!!
I tried with gwpagl01 but it doesn't seem to work, does the server automatically select it?

I have seen your other works, together with AlexxIT you are the best for me.
I'm not very good with code, I work as a systems engineer not a programmer.

Finally it would be nice to create an addon without the nodered flow, but I have no idea how to do it.

see you soon bye

**Comment by sdavides** [comment]
Wow, I entered the username and password into the file (I thought it took as an argument), and it works!!

**Comment by sdavides** [comment]
I have no idea how to enter the encrypted password in post nodered request,

But thank you very much, I'll include it in the readme.
Too bad you need python3 and pycryptodome.

if you have suggestions they are accepted.

**Comment by Wh1terat** [comment]
I'm not familiar with nodered but I'm sure the example code I provided could be refactored to suit your needs - sounds like a good learning exercise for you! 😃

**Comment by sdavides** [comment]
unfortunately with the static "appid" value present in the script, only the login page seems to work, the token is generated correctly, but for other pages the appid is incorrect.

I'm trying to figure out if it's always the same for everyone

**Comment by Wh1terat** [comment]
appid was always static - just varied between app versions and plaforms.
Could be the appid/appkey combo in my 2+ year old script are too old to query those endpoints, but seems odd.

**Comment by sdavides** [comment]
ok, then I can use my appid for everyone.

appkey is not needed, with an empty value it works

**Comment by sdavides** [comment]
I created the script, thank you very much

https://github.com/sdavides/AqaraPOST-Homeassistant/tree/main/generatejson#generate-token-from-username-and-password

**Comment by Wh1terat** [comment]
Hacky, but a start :+1:
